version: '3.3'
services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379
  postgresql:
    image: redis:alpine # ignore wrong image
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      OPEN_IN_BROWSER: postgresql://user:pass@localhost:3306/my_db
  api:
    image: nginx:alpine-slim
    restart: unless-stopped
    ports:
      - 1480:80
      - 1443:443
    environment:
      OPEN_IN_BROWSER: https://my-api-url.localhost/
  worker:
    image: nginx:alpine-slim
    restart: unless-stopped
